// Code generated by "go generate ./internal/agent/tools/hithink_finance/query"; DO NOT EDIT.
//
// 数据源：internal/agent/tools/hithink_finance/testdata/schema.json（真库快照）。
// 再生成：go generate ./internal/agent/tools/hithink_finance/query
// 或：cd internal/agent/tools/hithink_finance/query && go run ./gencatalog
//
// 快照被内联为静态字符串：工具描述在运行时不读任何文件。

package query

// schemaCatalog 是 SQLQueryTool.Description() 的表/列目录主体：各库的 v_* 视图
// 及其列清单（列名一律取自 testdata/schema.json），以及快照里没有的人工运营说明。
// 手改本文件会在下一次 go generate 时丢失；要改请改 query/gencatalog/main.go。
const schemaCatalog = `【market】行情
- v_daily_qfq(thscode, date, open, high, low, close, volume, turnover, forward_factor, currency, interval) — 前复权日线，做价量分析默认用这个
- v_daily_hfq(thscode, date, open, high, low, close, volume, turnover, backward_factor, currency, interval) — 后复权，看历史涨幅连续性
- v_daily(thscode, date, open, high, low, close, volume, turnover, currency, interval) — 原始不复权
- v_symbol(thscode, ticker, name, exchange, asset_type, currency) — 代码与名称对照，做 join 用这个

【indicators】技术指标
- v_indicators_daily(thscode, date, backend, computed_at, overlap_sma_5, overlap_sma_10, overlap_sma_20, overlap_sma_60, … 共 231 列) — 列族见下方说明
  列族前缀（其余为指标列，完整列名见快照）：
    momentum_*（rsi_*、macd_12_26_9_*、stoch_*…）、overlap_*（ma/ema/boll…）
    trend_*、volume_*、volatility_*、cycles_*（横向/纵向周期）
    statistics_*（beta、correl、linearreg、stddev…）、candles_cdl_*（K线形态）
  该表约 10GB，每天 19:00 刷新。
  ⚠ 没有 price 列；要价量必须与 market.v_daily_qfq 按 (thscode, date) join（两个库是独立只读连接，无法 ATTACH）。

【financials】基本面（全部以 thscode + period 为键，period 形如 2026Q2）
- v_income_statement(thscode, period, period_end_ms, report_date_ms, fiscal_year, fiscal_period, currency, basic_eps, operating_income, operating_costs, operating_expenses, operating_profit, profit_total, net_profit, parent_holder_net_profit, income_tax_expense, interest_expenses, manage_fee, sales_fee, research_and_development_expenses, raw_payload, captured_at) — 利润表
- v_balance_sheet(thscode, period, period_end_ms, report_date_ms, fiscal_year, fiscal_period, currency, total_current_assets, non_current_nets_total, assets_total, total_debt, holder_equity_total, cash, accounts_receivable, raw_payload, captured_at) — 资产负债表
- v_cash_flow_statement(thscode, period, period_end_ms, report_date_ms, fiscal_year, fiscal_period, currency, act_cash_flow_net, invest_cash_flow_net, financing_cash_flow_net, cash_equivalents_net_addition, pay_dividends_profits_interest_cash, pay_fixed_assets_etc_cash, raw_payload, captured_at) — 现金流量表
- v_financial_indicators(thscode, report, abilities_json, captured_at) — 能力指标打包在 abilities_json
- v_financial_indicators_detail(thscode, report, operating_income_yoy, operating_profit_yoy, total_assets_growth_ratio, fixed_asset_invest_expansion_ratio, parent_holder_net_profit_yoy, total_assets_net_ratio, … 共 27 列) — abilities 的展开列（yoy / roe / 毛利率等）
- v_valuation_latest(snapshot_date, thscode, ticker, name, pe_ttm, pe_mrq, pb_mrq, ps_ttm, pcf_ttm, raw_payload, captured_at) — 最新估值快照
- v_trading_calendar(trade_date, date_ms) — 交易日历

【index】指数与行业/概念归属（做行业对比、板块轮动的核心）
- v_index_universe(thscode, name, tag) — tag 取值 cn_concept / industry / region / tszs
- v_index_constituents(index_thscode, thscode, ticker, name) — 某指数/板块的成分股；⚠ 只有当前成分快照，无历史成分，历史回测有幸存者偏差
- v_index_daily(thscode, trade_date, date_ms, open, high, low, close, volume, turnover, raw_payload, captured_at) — 指数/板块行情
- v_index_latest(snapshot_date, thscode, last_price, price_change, price_change_ratio, open, high, low, volume, turnover, raw_payload, captured_at, name, tag) — 指数最新快照

【special】特色资金与情绪数据（按 trade_date / snapshot_date + thscode）
- v_limit_up_pool(trade_date, thscode, name, last_price, continue_day_cnt, limit_up_time, seal_money) — 涨停池
- v_limit_down_pool(trade_date, thscode, name, last_price, price_change_ratio, first_limit_time, last_limit_time) — 跌停池
- v_limit_break_pool(trade_date, thscode, name, last_price, open_times, price_change_ratio) — 炸板池 = 冲高回落 = 派发信号
- v_auction_snapshot(snapshot_date, thscode, ticker, name, auction_price, auction_pct, auction_volume, auction_amount, auction_unmatched, auction_turnover_pct, auction_yesterday_ratio_pct, auction_volume_ratio, pre_close_price, open_price, last_price, float_market_cap, stage, raw_payload, captured_at) — 集合竞价，盘前信号
- v_auction_benchmark(benchmark_date, thscode, ticker, name, auction_pct, tags, raw_payload, captured_at) — 集合竞价基准
- v_dragon_tiger(trade_date, board_type, thscode, name, net_value, net_rate, buy_value, sell_value, org_net_value, change, hot_rank, range_days) — 龙虎榜
- v_hot_stock(capture_date, period, rank, thscode, ticker, name, heat, rank_change, rank_trend, raw_payload, captured_at) — 热股榜
- v_hot_stock_history(history_date, rank, thscode, ticker, name, raw_payload, captured_at) — 热股榜历史
- v_hot_stock_rank_trend(thscode, trend_date, date_ms, rank, raw_payload, captured_at) — 热股排名趋势
- v_anomaly_list(capture_date, thscode, stock_name, tag_name, analysis_content, keyword_list, raw_payload, captured_at) — 异动
- v_skyrocket(capture_date, period, rank, thscode, ticker, name, heat, rank_change, rank_trend, raw_payload, captured_at) — 飙升榜

【fund】基金与 ETF
- v_etf_daily(thscode, trade_date, open, high, low, close, volume, turnover) — ETF 日线，可做 ETF 轮动
- v_etf_universe(thscode, ticker, name, exchange, asset_type, list_date, estab_date_ms, estab_date, captured_at) — ETF 列表
- v_etf_latest(thscode, ticker, name, exchange, asset_type, trade_date, last_price, change_pct, volume, turnover, turnover_ratio_pct) — ETF 最新快照
- v_fund_nav(thscode, nav_date, unit_nav, adj_nav, unit_nav_usable) — 基金净值（unit_nav / adj_nav / unit_nav_usable）
- v_fund_profile(thscode, ticker, fund_name, estab_date, company_id, mgmt_name, manager_name, fund_scale, unit_nav, captured_at) — 基金概况
- v_fund_holdings(fund_thscode, stock_thscode, stock_name, hold_ratio, position_count, security_market_value_rate_pct, period_increase_rate_pct, investment_rank, start_date_ms, end_date_ms, publish_date_ms, raw_payload, captured_at) — 基金重仓股
- v_fund_returns(fund_thscode, return_week, return_month, return_tmonth, return_hyear, return_year, return_twoyear, return_tyear, return_fyear, return_nowyear, return_now, raw_payload, captured_at) — 阶段收益
- v_fund_holders(fund_thscode, merge_scope, report_date_ms, ins_position, holder_amount, avg_holder_share, psnl_rate, mgmt_staff_hold_rate, raw_payload, captured_at) — 持有人结构
- v_fund_top_holders(fund_thscode, holder_name, holder_type, holder_code, rank, hold_share, hold_rate_pct, report_date_ms, publish_date_ms, raw_payload, captured_at) — 前十大持有人
- v_fund_company(company_id, company_name, company_type, established_date_ms, fund_count, scale, raw_payload, captured_at) — 基金公司

【futures】期货
- v_futures_daily(thscode, trade_date, open_price, high_price, low_price, close_price, volume, turnover) — 期货日线（open_price / high_price / low_price / close_price；无 open_interest）
- v_futures_varieties(variety_code, exchange_code, name, has_night_session, margin_rate, main_contract_thscode, trade_unit, tick_size, contract_multiplier) — 品种
- v_futures_contracts(thscode, ticker, name, variety_code, variety_name, exchange_code, list_date, end_date, last_trade_date, last_delivery_date) — 合约
- v_futures_latest(thscode, variety_code, exchange_code, name, trade_date, close_price, volume, turnover) — 最新快照
- v_futures_intraday(thscode, trade_date, session, bar_ts, price, volume, turnover) — 分时
- 品种多空持仓只有 raw_futures_positions_variety（无 v_ 视图）
`
